const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
} from '@expo/config-plugins'
const fs = require('node:fs')
const path = require('node:path')

/**
 * @en Expo config plugin: Android network_security_config pin-set from EXPO_PUBLIC_API_TLS_PINS (#220).
 * @es Plugin Expo: pin-set Android network_security_config desde EXPO_PUBLIC_API_TLS_PINS (#220).
 * @pt-BR Plugin Expo: pin-set Android network_security_config a partir de EXPO_PUBLIC_API_TLS_PINS (#220).
 *
 * Pins empty → no-op (dev / Expo Go / localhost). Host from EXPO_PUBLIC_API_TLS_PIN_HOST
 * or hostname of EXPO_PUBLIC_API_BASE_URL.
 */

function parsePins(raw) {
  return String(raw ?? '')
    .split(',')
    .map((p) => p.trim())
    .filter(Boolean)
}

function resolveHost(props) {
  if (props.host && String(props.host).trim()) return String(props.host).trim()
  const base = props.apiBaseUrl || process.env.EXPO_PUBLIC_API_BASE_URL || ''
  try {
    return new URL(base).hostname
  } catch {
    return ''
  }
}

function buildNetworkSecurityXml(host, pins, expiration) {
  const pinLines = pins.map((p) => `            <pin digest="SHA-256">${p}</pin>`).join('\n')
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by withApiTlsPinning (#220). Do not edit by hand. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="true">${host}</domain>
        <pin-set expiration="${expiration}">
${pinLines}
        </pin-set>
    </domain-config>
</network-security-config>
`
}

const withApiTlsPinning = (config, props = {}) => {
  const pins = parsePins(props.pins ?? process.env.EXPO_PUBLIC_API_TLS_PINS)
  if (pins.length === 0) {
    return config
  }
  const host = resolveHost({
    host: props.host ?? process.env.EXPO_PUBLIC_API_TLS_PIN_HOST,
    apiBaseUrl: props.apiBaseUrl ?? process.env.EXPO_PUBLIC_API_BASE_URL,
  })
  if (!host) {
    throw new Error(
      'EXPO_PUBLIC_API_TLS_PINS is set but host is missing. Set EXPO_PUBLIC_API_TLS_PIN_HOST or EXPO_PUBLIC_API_BASE_URL.',
    )
  }
  const expiration =
    props.expiration ?? process.env.EXPO_PUBLIC_API_TLS_PIN_EXPIRATION ?? '2028-12-31'

  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const resXml = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml')
      fs.mkdirSync(resXml, { recursive: true })
      fs.writeFileSync(
        path.join(resXml, 'network_security_config.xml'),
        buildNetworkSecurityXml(host, pins, expiration),
        'utf8',
      )
      return cfg
    },
  ])

  config = withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults)
    app.$['android:networkSecurityConfig'] = '@xml/network_security_config'
    return cfg
  })

  return config
}

module.exports = withApiTlsPinning
