/**
 * Generates `docs/api/openapi-reference.generated.md` from `docs/api/openapi.yaml`
 * using `@scalar/openapi-to-markdown`.
 *
 * @en Do not edit the output; regenerate with `npm run docs:openapi-md` or `docs:generate`.
 * @es No editar la salida; regenerar con `npm run docs:openapi-md` o `docs:generate`.
 * @pt-BR Não edite a saída; regenere com `npm run docs:openapi-md` ou `docs:generate`.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createMarkdownFromOpenApi } from '@scalar/openapi-to-markdown'
import YAML from 'yaml'

const ROOT = path.dirname(fileURLToPath(import.meta.url))
const REPO = path.join(ROOT, '..')
const OPENAPI_PATH = path.join(REPO, 'docs', 'api', 'openapi.yaml')
const OUT_PATH = path.join(REPO, 'docs', 'api', 'openapi-reference.generated.md')

const BANNER = `<!-- Generated by scripts/generate-openapi-markdown.ts + @scalar/openapi-to-markdown — do not edit by hand. Source: docs/api/openapi.yaml -->

`

async function main(): Promise<void> {
  const raw = fs.readFileSync(OPENAPI_PATH, 'utf-8')
  const doc = YAML.parse(raw) as Record<string, unknown>
  const md = await createMarkdownFromOpenApi(doc)
  fs.writeFileSync(OUT_PATH, `${BANNER}${md}`, 'utf-8')
  console.log('generate-openapi-markdown: wrote docs/api/openapi-reference.generated.md')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
